### ISSUE TITLE
不能同时使用三种数据源

### ISSUE THREAD

**Issue by cbyniiaii** [zhonglinlin1305/Spring#1]
是根据web.xml来决定使用那种方式的，并不是多种方式并存的。

**Comment by zhonglinlin1305** [comment]
可以切换的，在springwithjdbc的配置文件（applicationContextwithjdbc.xml）中配置多个数据源，然后在DatabaseContextHolder类中添加设置数据源，在同一个请求中，都可以动态切换，并不是web.xml决定的
